# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Desktop/nexys4_ddr_lab3.xdc

# IP: ip/binary_maze/binary_maze.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==binary_maze || ORIG_REF_NAME==binary_maze} -quiet] -quiet
