# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/giand/Documents/MIT/Senior_Fall/6.111/gims-labyrinth/gims_labyrinth/gims_labyrinth.srcs/sources_1/ip/binary_maze/binary_maze.xci
# IP: The module: 'binary_maze' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/giand/Documents/MIT/Senior_Fall/6.111/gims-labyrinth/gims_labyrinth/gims_labyrinth.srcs/sources_1/ip/binary_maze/binary_maze_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'binary_maze'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/giand/Documents/MIT/Senior_Fall/6.111/gims-labyrinth/gims_labyrinth/gims_labyrinth.srcs/sources_1/ip/binary_maze/binary_maze.xci
# IP: The module: 'binary_maze' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/giand/Documents/MIT/Senior_Fall/6.111/gims-labyrinth/gims_labyrinth/gims_labyrinth.srcs/sources_1/ip/binary_maze/binary_maze_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'binary_maze'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
