# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/giand/Documents/MIT/Senior_Fall/6.111/gims-labyrinth/gims_labyrinth/gims_labyrinth.srcs/sources_1/ip/corner_node_fifo/corner_node_fifo.xci
# IP: The module: 'corner_node_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/giand/Documents/MIT/Senior_Fall/6.111/gims-labyrinth/gims_labyrinth/gims_labyrinth.srcs/sources_1/ip/corner_node_fifo/corner_node_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'corner_node_fifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/giand/Documents/MIT/Senior_Fall/6.111/gims-labyrinth/gims_labyrinth/gims_labyrinth.srcs/sources_1/ip/corner_node_fifo/corner_node_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'corner_node_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/giand/Documents/MIT/Senior_Fall/6.111/gims-labyrinth/gims_labyrinth/gims_labyrinth.srcs/sources_1/ip/corner_node_fifo/corner_node_fifo.xci
# IP: The module: 'corner_node_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/giand/Documents/MIT/Senior_Fall/6.111/gims-labyrinth/gims_labyrinth/gims_labyrinth.srcs/sources_1/ip/corner_node_fifo/corner_node_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'corner_node_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/giand/Documents/MIT/Senior_Fall/6.111/gims-labyrinth/gims_labyrinth/gims_labyrinth.srcs/sources_1/ip/corner_node_fifo/corner_node_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'corner_node_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
